---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: entraid-jwt-authentication
  namespace: apps
spec:
  plugin:
    jwt:
      jwksUrl: "https://login.microsoftonline.com/common/discovery/v2.0/keys"
      forwardHeaders:
        X-APPID-CLAIM: appid
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: keycloak-jwt-authentication
spec:
  plugin:
    jwt:
      jwksUrl: http://keycloak-service.traefik-security.svc:8080/realms/keycloak-oauth/protocol/openid-connect/certs
      forwardHeaders:
        Group: group
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: test-opa
spec:
  plugin:
    opa:
      policy: |
        package jwt.policies

        allow {
          [_, encoded] := split(input.headers.Authorization, " ")
          [header, payload, signature] = io.jwt.decode(encoded)
          payload["email"] == "bibi@example.com"
        }
      forwardHeaders:
        Group: data.package.grp
