---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: proxy-custom-header
spec:
  headers:
    customRequestHeaders:
      X-Custom-Header: "Hello Traefik"
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: proxy-ratelimit
spec:
  rateLimit:
    average: 1
    burst: 1
    period: 10s