---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: entraid-jwt-authentication
  namespace: apps
spec:
  plugin:
    jwt:
      jwksUrl: "https://login.microsoftonline.com/common/discovery/v2.0/keys"
      forwardHeaders:
        X-APPID-CLAIM: appid
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: keycloak-jwt-authentication
spec:
  plugin:
    jwt:
      jwksUrl: http://keycloak-service.traefik-security.svc:8080/realms/traefik/protocol/openid-connect/certs
      forwardHeaders:
        Group: group
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: opa-authz
spec:
  plugin:
    opa:
      policy: |
        package jwt.policies

        default allow = false

        token := io.jwt.decode(split(input.headers.Authorization, " ")[1])[1]

        email := token["email"]
        issuer := token["iss"]
        domain := split(email, "@")[1]
        realm := split(issuer, "/")[count(split(issuer, "/")) - 1]

        allow {

        }
        
      forwardHeaders:
        Domain: data.jwt.policies.domain

