---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: gateway-api-middleware
spec:
  chain:
    middlewares:
    - name: proxy-custom-header
    - name: proxy-ratelimit
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: httpbin-gateway-api
spec:
  parentRefs:
    - name: traefik
      namespace: traefik
      sectionName: web
      kind: Gateway
  hostnames:
    - "gateway.traefik"
  rules:
    - matches:
        - path:
            type: PathPrefix 
            value: "/httpbin"
      backendRefs:
        - name: httpbin-svc
          port: 8000
      filters:
        - type: ExtensionRef
          extensionRef:
            group: traefik.io
            kind: Middleware
            name: httpbin-stripprefix
        - type: ExtensionRef
          extensionRef:
            group: traefik.io
            kind: Middleware
            name: gateway-api-middleware
