---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: httpbin-middleware
  annotations:
    hub.traefik.io/api: httpbin-api
spec:
  chain:
    middlewares:
    - name: proxy-custom-header
    - name: proxy-ratelimit
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: httpbin-route
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`httpbin.traefik`) || Host(`httpbin.traefik.localhost`)
      services:
        - name: httpbin-svc
          port: 8000
      middlewares:
        - name: httpbin-middleware
    - kind: Rule
      match: (Host(`gateway.traefik`) || Host(`gateway.traefik.localhost`)) && Header(`service`, `httpbin`)
      services:
        - name: httpbin-svc
          port: 8000
      middlewares:
        - name: httpbin-middleware
    - kind: Rule
      match: (Host(`gateway.traefik`) || Host(`gateway.traefik.localhost`)) && Query(`service`, `httpbin`)
      services:
        - name: httpbin-svc
          port: 8000
      middlewares:
        - name: httpbin-middleware